#include "game_menu_layout_legacy_controls.inl"
#include "game_menu_visibility.inl"
#include "game_menu_label_update.inl"
#include "game_menu_button_specs.inl"
#include "game_menu_button_rect.inl"
#include "game_menu_exit_door_rect.inl"
#include "game_menu_hit_test.inl"
