#include "game_menu_presentation_header.inl"
#include "game_menu_renderer_scene_state.inl"
#include "game_menu_hover_helpers.inl"
#include "game_menu_push_renderer_interaction.inl"
#include "game_menu_fade_amount.inl"
#include "game_menu_fade_draw.inl"
#include "game_menu_paint_main.inl"
