#pragma once

struct PlayerCameraRuntimeState {
    float turnLookBlend = 0.0f;
    float turnLookYaw = 0.0f;
    float manualLookYawDelta = 0.0f;
    float manualLookPitchDelta = 0.0f;
    float headScanTimer = 0.0f;
    float headScanDuration = 0.0f;
    float headScanCenter = 0.0f;
    float stopTimer = 0.0f;
    float nextLookBackTime = 9.0f;
    bool lookBack = false;
    bool junctionScanActive = false;
    int junctionScanCount = 0;
    std::array<float, 4> junctionScanYaws{};
    Tile junctionScanTile{-1000, -1000};
    float branchLookTimer = 0.0f;
    float branchLookDuration = 0.0f;
    float branchLookYaw = 0.0f;
    float branchLookPitch = -0.045f;
    float branchLookCooldown = 0.0f;
    bool branchLookPaused = false;
    Tile lastBranchLookTile{-1000, -1000};
    float roomSurveyTimer = 0.0f;
    float roomSurveyDuration = 0.0f;
    float roomSurveyCenter = 0.0f;
    float roomSurveySpan = 0.0f;
    float roomSurveyDirection = 1.0f;
    std::array<float, 6> roomSurveyYaws{};
    std::array<float, 6> roomSurveyPitches{};
    int roomSurveyYawCount = 0;
    int roomSurveyPitchCount = 0;
    float roomSurveyCooldown = 0.0f;
    Tile lastTile{-1000, -1000};
    Tile previousTile{-1000, -1000};
    std::vector<Tile> path;
    size_t pathIndex = 0;
    std::vector<XMFLOAT3> propLookPoints;
    float threatRepath = 0.0f;

    void ClearPath() {
        path.clear();
        pathIndex = 0;
    }
};

struct PlayerViewRuntimeState {
    XMFLOAT3 propLookTarget{};
    float propLookTimer = 0.0f;
    float propLookDuration = 0.0f;
    float propLookCooldown = 0.0f;
    float propLookScanSeed = 0.0f;
    XMFLOAT3 lastPropLookTarget{};
    bool hasLastPropLookTarget = false;
    float secondsSinceLookBack = 0.0f;
    bool exitSpotted = false;
    float exitLookBlend = 0.0f;
    XMFLOAT3 exitLookFocus{};
    float dangerLevel = 0.0f;
    float dreadLevel = 0.0f;
    float dreadMeterLevel = 0.0f;
    float monsterRunLaunchMeters = 3.0f;
    bool monsterRunLaunchActive = false;
    bool threatVisibleLast = false;
    float panicFlashlightTimer = 0.0f;
    float panicFlashlightDuration = 0.0f;
    bool monsterSpottedLast = false;
    float monsterSightDreadCooldown = 0.0f;
    float chaseLookBackTimer = 0.0f;
    float chaseLookBackDuration = 0.0f;
    float chaseLookBackCooldown = 0.0f;
    float chaseLookBackYaw = 0.0f;
    float chaseLookBackPitch = -0.035f;
    float stumbleTimer = 0.0f;
    float stumbleDuration = 0.0f;
    float stumbleYawOffset = 0.0f;
    float flashlightYaw = 0.0f;
    float flashlightPitch = -0.055f;
    float previousCameraYaw = 0.0f;
    float previousCameraPitch = -0.055f;
    XMFLOAT2 cameraMotionBlur{};
    float flashlightAgitation = 0.0f;
    float flashlightDartTimer = 0.0f;
    float flashlightDartDuration = 0.0f;
    float flashlightDartCooldown = 0.0f;
    float flashlightDartYaw = 0.0f;
    float flashlightDartPitch = 0.0f;
    float flashlightSnapTimer = 0.0f;
    float flashlightSnapDuration = 0.0f;
    float flashlightSnapCooldown = 0.0f;
    float flashlightSnapYaw = 0.0f;
    float flashlightSnapPitch = 0.0f;
    bool flashlightSnapSharp = false;
    float flashlightHoldYaw = 0.0f;
    float flashlightHoldPitch = 0.0f;
    float airFocusDistance = 3.5f;
    float ventReactionTimer = 0.0f;
    float ventReactionDuration = 0.0f;
    float ventReactionLookDelay = 0.0f;
    float ventReactionBackDuration = 0.0f;
    float ventReactionScanSeed = 0.0f;
    XMFLOAT3 ventReactionTarget{};
    XMFLOAT3 ventReactionAway{0.0f, 0.0f, 1.0f};
    float fadeInTimer = 1.2f;
    XMFLOAT3 exitStartCamera{};
    float exitStartYaw = 0.0f;
    bool exitScoreContinueReady = false;
    bool scoreContinuePressedLastFrame = false;
};
