#include "player_manual_control_service_context.inl"
#include "player_manual_control_input_build.inl"
#include "player_manual_control_services_build.inl"
#include "player_manual_interaction_dispatch.inl"
#include "player_manual_update.inl"
