#include "player_autopilot_panic_scan_pause.inl"
#include "player_autopilot_head_scan_update.inl"
#include "player_autopilot_stop_timer_update.inl"
#include "player_autopilot_vent_backaway.inl"
#include "player_autopilot_collision_recovery_gate.inl"
