#include "player_autopilot_speed_target.inl"
#include "player_autopilot_move_step.inl"
#include "player_autopilot_run_effort.inl"
#include "player_autopilot_camera_height.inl"
#include "player_autopilot_soft_stop_height.inl"
