#include "player_exit_route_clear.inl"
#include "player_exit_align_seconds.inl"
#include "player_exit_aligned_camera_target.inl"
#include "player_exit_transition_gate.inl"
#include "player_exit_attention_weight.inl"
