#include "player_main_menu_custom_view_enter.inl"
#include "player_main_menu_custom_view_return.inl"
#include "player_main_menu_custom_view_idle.inl"
#include "player_main_menu_custom_view_pointer.inl"
#include "player_main_menu_custom_view_finish.inl"
