#include "debug_slice_effect_step.inl"
#include "debug_slice_create_controls.inl"
#include "debug_slice_update_controls.inl"
#include "debug_slice_redraw_controls.inl"
#include "debug_slice_command.inl"
