#include "screensaver_renderer_settings.inl"
#include "screensaver_renderer_primary.inl"
#include "screensaver_renderer_clones.inl"
#include "screensaver_renderer_warmup.inl"
#include "screensaver_renderer_initialize.inl"
