#include "renderer_prop_placement_context.inl"
#include "renderer_loose_paper_mesh.inl"
#include "renderer_loose_paper_material.inl"
#include "renderer_loose_paper_add_one.inl"
#include "renderer_loose_paper_add_many.inl"
