#include "renderer_geometry_quad_primitives.inl"
#include "renderer_geometry_vector_math.inl"
#include "renderer_geometry_oriented_box.inl"
#include "renderer_geometry_floor_card.inl"
#include "renderer_geometry_ceiling_card.inl"
