#include "renderer_present_preflight_targets.inl"
#include "renderer_present_camera_vectors.inl"
#include "renderer_present_death_jitter_roll.inl"
#include "renderer_present_projection_fade.inl"
#include "renderer_present_flashlight_space.inl"
