#include "renderer_omukade_body_chain_arrays.inl"
#include "renderer_omukade_body_chain_support_up.inl"
#include "renderer_omukade_body_chain_points.inl"
#include "renderer_omukade_body_chain_uv.inl"
#include "renderer_omukade_body_chain_tangents.inl"
