#include "renderer_custom_menu_texture_gdi_bitmap.inl"
#include "renderer_custom_menu_texture_gdi_resources.inl"
#include "renderer_custom_menu_texture_gdi_draw_helpers.inl"
#include "renderer_custom_menu_texture_gdi_controls.inl"
#include "renderer_custom_menu_texture_gdi_finish.inl"
