    #include "renderer_overlay_draw.inl"
    #include "renderer_hud_notification.inl"
    #include "renderer_postprocess_overlay.inl"
    #include "renderer_game_hud_overlay.inl"
    #include "renderer_map_overlay_draw.inl"
