#include "renderer_omukade_visibility_gates.inl"
#include "renderer_omukade_visibility_trail_sample.inl"
#include "renderer_omukade_visibility_view_flags.inl"
#include "renderer_omukade_visibility_cpu_cull.inl"
#include "renderer_omukade_visibility_relevance.inl"
#include "renderer_omukade_detail_level.inl"
#include "renderer_omukade_render_basis.inl"
