    #include "renderer_dynamic_primitives.inl"
    #include "renderer_dynamic_skull_mesh.inl"
    #include "renderer_dynamic_menu_geometry.inl"
    #include "renderer_omukade_geometry.inl"
    #include "renderer_dynamic_effect_geometry.inl"
    #include "renderer_dynamic_geometry_update.inl"
