#include "renderer_omukade_body_surface_loop.inl"
#include "renderer_omukade_body_surface_wall_choice.inl"
#include "renderer_omukade_body_surface_center.inl"
#include "renderer_omukade_body_surface_up.inl"
#include "renderer_omukade_body_surface_commit.inl"
