    #include "scare_sensory_helpers.inl"
    #include "scare_lamp_spark_events.inl"
    #include "scare_vent_events.inl"
    #include "scare_event_update.inl"
    #include "scare_particle_updates.inl"
