#pragma once

// Config dialog tab labels, notes, and full settings field table.

const wchar_t* kConfigTabs[kConfigMaxTabCount] = {
    L"Renderer",
    L"Maze",
    L"Textures",
    L"Lighting",
    L"Camera AI",
    L"Camera FX",
    L"Atmosphere",
    L"Monster"
};

const wchar_t* kConfigNotes[kConfigMaxTabCount] = {
    L"Renderer device policy. Keep WARP disabled to require hardware GPU rendering.",
    L"Maze dimensions are forced odd. Per-run variation jitters Camera AI, Flashlight Motion, and non-blood/flesh Atmosphere values by up to 15%; room +/- fields are explicit integer ranges.",
    L"PBR stems accept Backrooms names like <stem>_color_4k.jpg and Substance names like <stem>_Color.jpg. Empty floor/ceiling stems use built-in textures.",
    L"Flashlight shadows, lamp population, black haze, and procedural corner ambient occlusion.",
    L"Camera pathing, head movement, room scanning, and look-back behavior.",
    L"Independent flashlight motion, entrance fades, and the exit door transition.",
    L"Paper, props, water damage, in-ceiling lamp failures, and spark particles.",
    L"Monster scale, chase logic, dread response, and mesh orientation. On this tab, right-drag the preview to orbit and use the wheel to zoom."
};

const ConfigFieldDef kConfigFields[] = {
    {0, 0, kConfigFieldBaseId + 0, L"GPU Device", L"Renderer", L"AllowWarpFallback", L"WARP fallback", L"0", ConfigFieldKind::Bool, 0},

    {1, 0, kConfigFieldBaseId + 1, L"Maze Size", L"Maze", L"Width", L"Width", L"25", ConfigFieldKind::Text, 90},
    {1, 0, kConfigFieldBaseId + 2, L"Maze Size", L"Maze", L"Height", L"Height", L"25", ConfigFieldKind::Text, 90},
    {1, 0, kConfigFieldBaseId + 104, L"Maze Size", L"Maze", L"TileWidthMeters", L"Tile width meters", L"1.6", ConfigFieldKind::Text, 90},
    {1, 0, kConfigFieldBaseId + 105, L"Maze Size", L"Maze", L"TileLengthMeters", L"Tile length meters", L"1.6", ConfigFieldKind::Text, 90},
    {1, 0, kConfigFieldBaseId + 106, L"Maze Size", L"Maze", L"WallHeightMeters", L"Wall/ceiling height", L"2.85", ConfigFieldKind::Text, 90},
    {1, 1, kConfigFieldBaseId + 3, L"Room Generation", L"Maze", L"RoomCount", L"Room count", L"3", ConfigFieldKind::Text, 90},
    {1, 1, kConfigFieldBaseId + 4, L"Room Generation", L"Maze", L"RoomMinRadius", L"Room min radius", L"1.5", ConfigFieldKind::Text, 90},
    {1, 1, kConfigFieldBaseId + 5, L"Room Generation", L"Maze", L"RoomMaxRadius", L"Room max radius", L"3", ConfigFieldKind::Text, 90},
    {1, 1, kConfigFieldBaseId + 113, L"Room Generation", L"Maze", L"RoomCountRange", L"Room count +/-", L"1", ConfigFieldKind::Text, 90},
    {1, 1, kConfigFieldBaseId + 114, L"Room Generation", L"Maze", L"RoomMinRadiusRange", L"Min radius +/-", L"1", ConfigFieldKind::Text, 90},
    {1, 1, kConfigFieldBaseId + 115, L"Room Generation", L"Maze", L"RoomMaxRadiusRange", L"Max radius +/-", L"1", ConfigFieldKind::Text, 90},
    {1, 1, kConfigFieldBaseId + 180, L"Extra Connectors", L"Maze", L"ExtraConnectorMinRatio", L"Min wall openings", L"0.015", ConfigFieldKind::Text, 90},
    {1, 1, kConfigFieldBaseId + 181, L"Extra Connectors", L"Maze", L"ExtraConnectorMaxRatio", L"Max wall openings", L"0.05", ConfigFieldKind::Text, 90},
    {1, 1, kConfigFieldBaseId + 182, L"Wall Features", L"Maze", L"WallFeatureFrequency", L"Feature interval", L"20", ConfigFieldKind::Text, 90},
    {1, 1, kConfigFieldBaseId + 183, L"Wall Features", L"Maze", L"WallFeatureFrequencySpread", L"Interval spread", L"1", ConfigFieldKind::Text, 90},
    {1, 1, kConfigFieldBaseId + 184, L"Save Items", L"Maze", L"SaveItemMinPerLayer", L"Min per layer", L"1", ConfigFieldKind::Text, 90},
    {1, 1, kConfigFieldBaseId + 185, L"Save Items", L"Maze", L"SaveItemMaxPerLayer", L"Max per layer", L"3", ConfigFieldKind::Text, 90},
    {1, 1, kConfigFieldBaseId + 186, L"Save Items", L"Maze", L"SaveItemLevelChance", L"Level chance", L"0.15", ConfigFieldKind::Text, 90},
    {1, 0, kConfigFieldBaseId + 49, L"Maze Size", L"Maze", L"RandomSeed", L"Random seed (0=random)", L"0", ConfigFieldKind::Text, 90},
    {1, 0, kConfigFieldBaseId + 128, L"Maze Debug", L"Maze", L"MapOverlay", L"Show map overlay", L"1", ConfigFieldKind::Bool, 0},
    {1, 1, kConfigFieldBaseId + 100, L"Randomization", L"Randomization", L"RunVariation", L"Per-run variation", L"0.1", ConfigFieldKind::Text, 90},

    {2, 0, kConfigFieldBaseId + 6, L"Texture Files", L"Textures", L"AssetFolder", L"Asset folder", L"assets\\PBRs", ConfigFieldKind::Text, 170},
    {2, 0, kConfigFieldBaseId + 7, L"Texture Files", L"Textures", L"WallStem", L"Wall PBR stem", L"backrooms_wall", ConfigFieldKind::Text, 150},
    {2, 0, kConfigFieldBaseId + 8, L"Texture Files", L"Textures", L"FloorStem", L"Floor PBR stem", L"downloads\\Fabric029_4K-JPG\\Fabric029_4K-JPG", ConfigFieldKind::Text, 150},
    {2, 0, kConfigFieldBaseId + 9, L"Texture Files", L"Textures", L"CeilingStem", L"Ceiling PBR stem", L"downloads\\OfficeCeiling001_4K-JPG\\OfficeCeiling001_4K-JPG", ConfigFieldKind::Text, 150},
    {2, 0, kConfigFieldBaseId + 78, L"Texture Files", L"Textures", L"FleshStem", L"Flesh PBR stem", L"downloads\\Others001_4k\\others_0001", ConfigFieldKind::Text, 170},
    {2, 1, kConfigFieldBaseId + 10, L"Texture Scale", L"Textures", L"WallScaleMeters", L"Wall scale meters", L"1.8", ConfigFieldKind::Text, 90},
    {2, 1, kConfigFieldBaseId + 11, L"Texture Scale", L"Textures", L"FloorScaleMeters", L"Floor scale meters", L"1.8", ConfigFieldKind::Text, 90},
    {2, 1, kConfigFieldBaseId + 12, L"Texture Scale", L"Textures", L"CeilingScaleMeters", L"Ceiling scale meters (0=auto 3x3)", L"0", ConfigFieldKind::Text, 90},
    {2, 1, kConfigFieldBaseId + 13, L"Normal Maps", L"Textures", L"UseExternalNormals", L"Use external normal maps", L"1", ConfigFieldKind::Bool, 0},
    {2, 1, kConfigFieldBaseId + 14, L"Normal Maps", L"Textures", L"MaxNormalMapMB", L"Max normal map MB", L"512", ConfigFieldKind::Text, 90},

    {3, 0, kConfigFieldBaseId + 15, L"Flashlight", L"Lighting", L"FlashlightIntensity", L"Flashlight intensity", L"1", ConfigFieldKind::Text, 90},
    {3, 0, kConfigFieldBaseId + 16, L"Flashlight", L"Lighting", L"FlashlightAttenuation", L"Flashlight attenuation", L"0.115", ConfigFieldKind::Text, 90},
    {3, 0, kConfigFieldBaseId + 48, L"Flashlight", L"Lighting", L"FlashlightConeDegrees", L"Cone width degrees", L"80", ConfigFieldKind::Text, 90},
    {3, 0, kConfigFieldBaseId + 17, L"Flashlight", L"Lighting", L"AmbientLight", L"Ambient light", L"0", ConfigFieldKind::Text, 90},
    {3, 0, kConfigFieldBaseId + 43, L"Flashlight", L"Lighting", L"FlashlightShadows", L"Realtime shadows", L"1", ConfigFieldKind::Bool, 0},
    {3, 0, kConfigFieldBaseId + 44, L"Flashlight", L"Lighting", L"FlashlightShadowStrength", L"Shadow strength", L"0.72", ConfigFieldKind::Text, 90},
    {3, 0, kConfigFieldBaseId + 45, L"Flashlight", L"Lighting", L"FlashlightShadowDistanceMeters", L"Shadow distance meters", L"18", ConfigFieldKind::Text, 90},
    {3, 0, kConfigFieldBaseId + 46, L"Flashlight", L"Lighting", L"FlashlightShadowBias", L"Shadow bias", L"0.00075", ConfigFieldKind::Text, 90},
    {3, 0, kConfigFieldBaseId + 47, L"Flashlight", L"Lighting", L"FlashlightShadowMapSize", L"Shadow map size", L"2048", ConfigFieldKind::Text, 90},
    {3, 1, kConfigFieldBaseId + 18, L"Ceiling Lamps", L"Lighting", L"LampIntensity", L"Lamp intensity", L"1.45", ConfigFieldKind::Text, 90},
    {3, 1, kConfigFieldBaseId + 19, L"Ceiling Lamps", L"Lighting", L"LampSpacing", L"Lamp spacing", L"3.2", ConfigFieldKind::Text, 90},
    {3, 1, kConfigFieldBaseId + 20, L"Ceiling Lamps", L"Lighting", L"LampOnRatio", L"Lamp on ratio", L"0.95", ConfigFieldKind::Text, 90},
    {3, 1, kConfigFieldBaseId + 21, L"Ceiling Lamps", L"Lighting", L"LampFlickerRatio", L"Lamp flicker ratio", L"0.1", ConfigFieldKind::Text, 90},
    {3, 1, kConfigFieldBaseId + 22, L"Ceiling Lamps", L"Lighting", L"BrokenZoneRatio", L"Broken zone ratio", L"0.05", ConfigFieldKind::Text, 90},
    {3, 1, kConfigFieldBaseId + 50, L"Ceiling Lamps", L"Lighting", L"DarkLampVisibleRatio", L"Visible dark fixtures", L"1.0", ConfigFieldKind::Text, 90},
    {3, 0, kConfigFieldBaseId + 23, L"Fog / Haze", L"Lighting", L"FogStartMeters", L"Fog start meters", L"0", ConfigFieldKind::Text, 90},
    {3, 0, kConfigFieldBaseId + 24, L"Fog / Haze", L"Lighting", L"FogEndMeters", L"Fog end meters", L"28", ConfigFieldKind::Text, 90},
    {3, 0, kConfigFieldBaseId + 25, L"Fog / Haze", L"Lighting", L"FogDarkness", L"Fog darkness", L"1", ConfigFieldKind::Text, 90},
    {3, 1, kConfigFieldBaseId + 26, L"Ambient Occlusion", L"Lighting", L"CornerAOIntensity", L"Corner AO intensity", L"0.45", ConfigFieldKind::Text, 90},
    {3, 1, kConfigFieldBaseId + 27, L"Ambient Occlusion", L"Lighting", L"CornerAORadius", L"Corner AO radius", L"0.5", ConfigFieldKind::Text, 90},
    {3, 1, kConfigFieldBaseId + 28, L"Ambient Occlusion", L"Lighting", L"FloorCeilingAOIntensity", L"Floor/ceiling AO", L"0.3", ConfigFieldKind::Text, 90},
    {3, 0, kConfigFieldBaseId + 41, L"Post Processing", L"Lighting", L"Exposure", L"Exposure", L"1", ConfigFieldKind::Text, 90},
    {3, 0, kConfigFieldBaseId + 42, L"Post Processing", L"Lighting", L"Gamma", L"Gamma", L"1", ConfigFieldKind::Text, 90},
    {3, 0, kConfigFieldBaseId + 148, L"Post Processing", L"Lighting", L"MotionBlurAmount", L"Motion blur", L"0.18", ConfigFieldKind::Text, 90},
    {3, 0, kConfigFieldBaseId + 149, L"Post Processing", L"Lighting", L"BloomAmount", L"Bloom", L"0.22", ConfigFieldKind::Text, 90},
    {3, 0, kConfigFieldBaseId + 150, L"Post Processing", L"Lighting", L"LensDirtAmount", L"Lens dirt", L"0.18", ConfigFieldKind::Text, 90},

    {4, 0, kConfigFieldBaseId + 29, L"Movement Speeds", L"CameraAI", L"WalkSpeed", L"Walk speed", L"1.692", ConfigFieldKind::Text, 90},
    {4, 0, kConfigFieldBaseId + 30, L"Movement Speeds", L"CameraAI", L"RoomSpeed", L"Room speed", L"1.45", ConfigFieldKind::Text, 90},
    {4, 0, kConfigFieldBaseId + 31, L"Movement Speeds", L"CameraAI", L"RunSpeed", L"Run speed", L"3.05", ConfigFieldKind::Text, 90},
    {4, 1, kConfigFieldBaseId + 32, L"Look Ahead", L"CameraAI", L"TurnLookAheadTiles", L"Turn look-ahead tiles", L"2.1", ConfigFieldKind::Text, 90},
    {4, 1, kConfigFieldBaseId + 33, L"Look Ahead", L"CameraAI", L"RoomLookAheadTiles", L"Room look-ahead tiles", L"2.4", ConfigFieldKind::Text, 90},
    {4, 1, kConfigFieldBaseId + 34, L"Look Ahead", L"CameraAI", L"RoomPauseChance", L"Room pause chance", L"0.62", ConfigFieldKind::Text, 90},
    {4, 1, kConfigFieldBaseId + 35, L"Look Ahead", L"CameraAI", L"JunctionScanChance", L"Junction scan chance", L"0.88", ConfigFieldKind::Text, 90},
    {4, 1, kConfigFieldBaseId + 36, L"Look Ahead", L"CameraAI", L"ScanAngleDegrees", L"Scan angle degrees", L"55", ConfigFieldKind::Text, 90},
    {4, 1, kConfigFieldBaseId + 54, L"Look Ahead", L"CameraAI", L"JunctionScanBaseSeconds", L"Junction base seconds", L"0.85", ConfigFieldKind::Text, 90},
    {4, 1, kConfigFieldBaseId + 55, L"Look Ahead", L"CameraAI", L"JunctionScanBranchSeconds", L"Junction branch seconds", L"1.08", ConfigFieldKind::Text, 90},
    {4, 0, kConfigFieldBaseId + 37, L"Look Back / Head Motion", L"CameraAI", L"LookBackMinSeconds", L"Look-back min seconds", L"5", ConfigFieldKind::Text, 90},
    {4, 0, kConfigFieldBaseId + 38, L"Look Back / Head Motion", L"CameraAI", L"LookBackMaxSeconds", L"Look-back max seconds", L"90", ConfigFieldKind::Text, 90},
    {4, 0, kConfigFieldBaseId + 39, L"Look Back / Head Motion", L"CameraAI", L"HeadBobAmount", L"Head bob amount", L"0.0825", ConfigFieldKind::Text, 90},
    {4, 0, kConfigFieldBaseId + 40, L"Look Back / Head Motion", L"CameraAI", L"SideSwayAmount", L"Side sway amount", L"0.025", ConfigFieldKind::Text, 90},

    {5, 0, kConfigFieldBaseId + 51, L"Flashlight Motion", L"CameraFX", L"FlashlightSwayAmount", L"Independent sway", L"3", ConfigFieldKind::Text, 90},
    {5, 0, kConfigFieldBaseId + 52, L"Flashlight Motion", L"CameraFX", L"FlashlightFollowSpeed", L"Follow speed", L"2", ConfigFieldKind::Text, 90},
    {5, 0, kConfigFieldBaseId + 53, L"Flashlight Motion", L"CameraFX", L"FlashlightPanicDartAmount", L"Panic dart amount", L"3", ConfigFieldKind::Text, 90},
    {5, 1, kConfigFieldBaseId + 56, L"Exit Door Transition", L"CameraFX", L"ExitDoorOpenSeconds", L"Door open seconds", L"1.75", ConfigFieldKind::Text, 90},
    {5, 1, kConfigFieldBaseId + 57, L"Exit Door Transition", L"CameraFX", L"ExitStepSeconds", L"Step-through seconds", L"1.85", ConfigFieldKind::Text, 90},
    {5, 1, kConfigFieldBaseId + 58, L"Exit Door Transition", L"CameraFX", L"ExitFadeSeconds", L"Fade-out seconds", L"1.1", ConfigFieldKind::Text, 90},
    {5, 1, kConfigFieldBaseId + 59, L"Exit Door Transition", L"CameraFX", L"ExitStepDistance", L"Step distance", L"2.35", ConfigFieldKind::Text, 90},
    {5, 1, kConfigFieldBaseId + 60, L"Exit Door Transition", L"CameraFX", L"FadeInSeconds", L"New maze fade-in", L"1.25", ConfigFieldKind::Text, 90},

    {6, 0, kConfigFieldBaseId + 61, L"Clutter Density", L"Atmosphere", L"PaperDensity", L"Loose paper density", L"1", ConfigFieldKind::Text, 90},
    {6, 0, kConfigFieldBaseId + 62, L"Clutter Density", L"Atmosphere", L"HallwayPaperRunDensity", L"Paper hallway density", L"1", ConfigFieldKind::Text, 90},
    {6, 0, kConfigFieldBaseId + 63, L"Clutter Density", L"Atmosphere", L"ChairDensity", L"Chair density", L"1", ConfigFieldKind::Text, 90},
    {6, 0, kConfigFieldBaseId + 179, L"Clutter Density", L"Atmosphere", L"WaterDamageEnabled", L"Enable water damage", L"0", ConfigFieldKind::Bool, 0},
    {6, 0, kConfigFieldBaseId + 66, L"Clutter Density", L"Atmosphere", L"WaterDamageDensity", L"Water damage density", L"0", ConfigFieldKind::Text, 90},
    {6, 0, kConfigFieldBaseId + 117, L"Clutter Density", L"Atmosphere", L"MetalCabinetDensity", L"Metal cabinet density", L"0.85", ConfigFieldKind::Text, 90},
    {6, 0, kConfigFieldBaseId + 101, L"Scare Timing", L"Atmosphere", L"JumpscareFrequency", L"Jumpscare frequency", L"0.15", ConfigFieldKind::Text, 90},
    {6, 1, kConfigFieldBaseId + 67, L"Spark Particles", L"Atmosphere", L"SparkParticles", L"Enable sparks", L"1", ConfigFieldKind::Bool, 0},
    {6, 1, kConfigFieldBaseId + 68, L"Spark Particles", L"Atmosphere", L"SparkEmitterRatio", L"Broken lamp spark ratio", L"0.15", ConfigFieldKind::Text, 90},
    {6, 1, kConfigFieldBaseId + 69, L"Spark Particles", L"Atmosphere", L"SparkBurstMinSeconds", L"Burst min seconds", L"2.8", ConfigFieldKind::Text, 90},
    {6, 1, kConfigFieldBaseId + 70, L"Spark Particles", L"Atmosphere", L"SparkBurstMaxSeconds", L"Burst max seconds", L"8.8", ConfigFieldKind::Text, 90},
    {6, 1, kConfigFieldBaseId + 71, L"Spark Particles", L"Atmosphere", L"SparkMaxParticles", L"Max spark particles", L"160", ConfigFieldKind::Text, 90},
    {6, 1, kConfigFieldBaseId + 72, L"Spark Particles", L"Atmosphere", L"SparkSize", L"Spark size", L"1", ConfigFieldKind::Text, 90},
    {6, 1, kConfigFieldBaseId + 144, L"Air Particles", L"Atmosphere", L"AirParticles", L"Enable air motes", L"1", ConfigFieldKind::Bool, 0},
    {6, 1, kConfigFieldBaseId + 145, L"Air Particles", L"Atmosphere", L"AirParticleDensity", L"Mote density", L"1", ConfigFieldKind::Text, 90},
    {6, 1, kConfigFieldBaseId + 146, L"Air Particles", L"Atmosphere", L"AirParticleSize", L"Mote size", L"1", ConfigFieldKind::Text, 90},
    {6, 1, kConfigFieldBaseId + 147, L"Air Particles", L"Atmosphere", L"AirParticleBlur", L"Focus blur", L"1", ConfigFieldKind::Text, 90},
    {6, 0, kConfigFieldBaseId + 79, L"Blood / Flesh Scares", L"Atmosphere", L"BloodSplatterDensity", L"Blood density", L"0", ConfigFieldKind::Text, 90},
    {6, 0, kConfigFieldBaseId + 80, L"Blood / Flesh Scares", L"Atmosphere", L"BloodBurstCount", L"Paint burst count", L"25", ConfigFieldKind::Text, 90},
    {6, 0, kConfigFieldBaseId + 81, L"Blood / Flesh Scares", L"Atmosphere", L"BloodWetness", L"Wet reflectivity", L"0.995", ConfigFieldKind::Text, 90},
    {6, 0, kConfigFieldBaseId + 118, L"Blood / Flesh Scares", L"Atmosphere", L"BloodStreamCount", L"Wall stream count", L"30", ConfigFieldKind::Text, 90},
    {6, 0, kConfigFieldBaseId + 119, L"Blood / Flesh Scares", L"Atmosphere", L"BloodStreamThickness", L"Stream thickness", L"0.88", ConfigFieldKind::Text, 90},
    {6, 0, kConfigFieldBaseId + 127, L"Blood / Flesh Scares", L"Atmosphere", L"BloodShaderQuality", L"Blood shader quality", L"1", ConfigFieldKind::Text, 90},
    {6, 0, kConfigFieldBaseId + 120, L"Blood / Flesh Scares", L"Atmosphere", L"BloodWorldCoverage", L"Blood world coverage", L"1", ConfigFieldKind::Text, 90},
    {6, 0, kConfigFieldBaseId + 121, L"Blood / Flesh Scares", L"Atmosphere", L"BloodWorldFlickerIntensity", L"Blood world intensity", L"1", ConfigFieldKind::Text, 90},
    {6, 1, kConfigFieldBaseId + 122, L"Blood World", L"Atmosphere", L"BloodWorldFlicker", L"Enable blood world", L"1", ConfigFieldKind::Bool, 0},
    {6, 1, kConfigFieldBaseId + 123, L"Blood World", L"Atmosphere", L"BloodWorldAlwaysOn", L"Blood world always on", L"0", ConfigFieldKind::Bool, 0},
    {6, 1, kConfigFieldBaseId + 124, L"Blood World", L"Atmosphere", L"BloodWorldFlickerMinSeconds", L"Flicker min seconds", L"1500", ConfigFieldKind::Text, 90},
    {6, 1, kConfigFieldBaseId + 125, L"Blood World", L"Atmosphere", L"BloodWorldFlickerMaxSeconds", L"Flicker max seconds", L"4800", ConfigFieldKind::Text, 90},
    {6, 1, kConfigFieldBaseId + 126, L"Blood World", L"Atmosphere", L"BloodWorldFlickerDuration", L"Flicker duration", L"0.35", ConfigFieldKind::Text, 90},
    {6, 1, kConfigFieldBaseId + 129, L"Blood World", L"Atmosphere", L"BloodStudyView", L"Fixed blood study view", L"0", ConfigFieldKind::Bool, 0},
    {6, 1, kConfigFieldBaseId + 82, L"Blood / Flesh Scares", L"Atmosphere", L"FleshFlicker", L"Enable flesh flicker", L"1", ConfigFieldKind::Bool, 0},
    {6, 1, kConfigFieldBaseId + 87, L"Blood / Flesh Scares", L"Atmosphere", L"FleshAlwaysOn", L"Flesh always on", L"0", ConfigFieldKind::Bool, 0},
    {6, 1, kConfigFieldBaseId + 88, L"Blood / Flesh Scares", L"Atmosphere", L"FleshWetness", L"Flesh wetness", L"0.995", ConfigFieldKind::Text, 90},
    {6, 1, kConfigFieldBaseId + 89, L"Blood / Flesh Scares", L"Atmosphere", L"FleshParallaxScale", L"Flesh relief scale", L"0.22", ConfigFieldKind::Text, 90},
    {6, 1, kConfigFieldBaseId + 83, L"Blood / Flesh Scares", L"Atmosphere", L"FleshFlickerMinSeconds", L"Flicker min seconds", L"1500", ConfigFieldKind::Text, 90},
    {6, 1, kConfigFieldBaseId + 84, L"Blood / Flesh Scares", L"Atmosphere", L"FleshFlickerMaxSeconds", L"Flicker max seconds", L"4800", ConfigFieldKind::Text, 90},
    {6, 1, kConfigFieldBaseId + 85, L"Blood / Flesh Scares", L"Atmosphere", L"FleshFlickerDuration", L"Flicker duration", L"0.35", ConfigFieldKind::Text, 90},
    {6, 1, kConfigFieldBaseId + 86, L"Blood / Flesh Scares", L"Atmosphere", L"FleshFlickerIntensity", L"Flicker intensity", L"1", ConfigFieldKind::Text, 90},
    {6, 0, kConfigFieldBaseId + 151, L"Effect Tuning", L"EffectTuning", L"BloodLoopSeconds", L"Blood loop seconds", L"56", ConfigFieldKind::Text, 90},
    {6, 0, kConfigFieldBaseId + 152, L"Effect Tuning", L"EffectTuning", L"BloodFullSpreadAge", L"Blood final age", L"48", ConfigFieldKind::Text, 90},
    {6, 0, kConfigFieldBaseId + 153, L"Effect Tuning", L"EffectTuning", L"WaterLoopSeconds", L"Water loop seconds", L"7.5", ConfigFieldKind::Text, 90},
    {6, 0, kConfigFieldBaseId + 154, L"Effect Tuning", L"EffectTuning", L"AirVentLoopSeconds", L"Vent loop seconds", L"6.2", ConfigFieldKind::Text, 90},
    {6, 0, kConfigFieldBaseId + 155, L"Effect Tuning", L"EffectTuning", L"BrokenLampLoopSeconds", L"Lamp loop seconds", L"5.2", ConfigFieldKind::Text, 90},
    {6, 0, kConfigFieldBaseId + 156, L"Effect Tuning", L"EffectTuning", L"StaticLoopSeconds", L"Static loop seconds", L"8", ConfigFieldKind::Text, 90},
    {6, 0, kConfigFieldBaseId + 157, L"Effect Tuning", L"EffectTuning", L"BrokenLampSparkIntensityMin", L"Spark min", L"2.2", ConfigFieldKind::Text, 90},
    {6, 0, kConfigFieldBaseId + 158, L"Effect Tuning", L"EffectTuning", L"BrokenLampSparkIntensityMax", L"Spark max", L"4.1", ConfigFieldKind::Text, 90},
    {6, 1, kConfigFieldBaseId + 159, L"Effect Tuning", L"EffectTuning", L"BrokenLampChainIntensityScale", L"Chain intensity scale", L"0.70", ConfigFieldKind::Text, 90},
    {6, 1, kConfigFieldBaseId + 160, L"Effect Tuning", L"EffectTuning", L"BrokenLampChainBurstsMin", L"Chain bursts min", L"1", ConfigFieldKind::Text, 90},
    {6, 1, kConfigFieldBaseId + 161, L"Effect Tuning", L"EffectTuning", L"BrokenLampChainBurstsMax", L"Chain bursts max", L"3", ConfigFieldKind::Text, 90},
    {6, 1, kConfigFieldBaseId + 162, L"Effect Tuning", L"EffectTuning", L"AirVentSteamIntensityMin", L"Vent steam min", L"1.9", ConfigFieldKind::Text, 90},
    {6, 1, kConfigFieldBaseId + 163, L"Effect Tuning", L"EffectTuning", L"AirVentSteamIntensityMax", L"Vent steam max", L"3.2", ConfigFieldKind::Text, 90},
    {6, 1, kConfigFieldBaseId + 164, L"Effect Tuning", L"EffectTuning", L"AirVentPanelDropEvery", L"Debug vent drop every", L"3", ConfigFieldKind::Text, 90},
    {6, 1, kConfigFieldBaseId + 165, L"Effect Tuning", L"EffectTuning", L"AirVentPanelDropChance", L"Runtime vent drop chance", L"0.1", ConfigFieldKind::Text, 90},

    {7, 0, kConfigFieldBaseId + 73, L"Creature", L"Monster", L"MonsterScale", L"Scale", L"1", ConfigFieldKind::Text, 90},
    {7, 0, kConfigFieldBaseId + 74, L"Creature", L"Monster", L"MonsterSpeed", L"Base speed multiplier", L"0.68", ConfigFieldKind::Text, 90},
    {7, 0, kConfigFieldBaseId + 75, L"Creature", L"Monster", L"MonsterSprintSpeed", L"Sprint speed multiplier", L"0.88", ConfigFieldKind::Text, 90},
    {7, 0, kConfigFieldBaseId + 102, L"Face Mesh", L"Monster", L"SkullMesh", L"Mask mesh", L"assets\\models\\monster_face_mask\\horror_mask.obj", ConfigFieldKind::Text, 170},
    {7, 0, kConfigFieldBaseId + 130, L"Face Mesh", L"Monster", L"AlternateSkullMesh", L"Alternate mask mesh", L"", ConfigFieldKind::Text, 170},
    {7, 0, kConfigFieldBaseId + 131, L"Face Mesh", L"Monster", L"AlternateSkullChance", L"Alternate mask chance", L"0", ConfigFieldKind::Text, 90},
    {7, 0, kConfigFieldBaseId + 103, L"Face Mesh", L"Monster", L"SkullMaxTriangles", L"Mesh triangles", L"65000", ConfigFieldKind::Text, 90},
    {7, 0, kConfigFieldBaseId + 132, L"Deer Orientation", L"Monster", L"SkullYawDegrees", L"Deer yaw degrees", L"0", ConfigFieldKind::Text, 58},
    {7, 0, kConfigFieldBaseId + 133, L"Deer Orientation", L"Monster", L"SkullPitchDegrees", L"Deer pitch degrees", L"0", ConfigFieldKind::Text, 58},
    {7, 0, kConfigFieldBaseId + 134, L"Deer Orientation", L"Monster", L"SkullRollDegrees", L"Deer roll degrees", L"0", ConfigFieldKind::Text, 58},
    {7, 0, kConfigFieldBaseId + 135, L"Ram Orientation", L"Monster", L"AlternateSkullYawDegrees", L"Ram yaw degrees", L"-90", ConfigFieldKind::Text, 58},
    {7, 0, kConfigFieldBaseId + 136, L"Ram Orientation", L"Monster", L"AlternateSkullPitchDegrees", L"Ram pitch degrees", L"0", ConfigFieldKind::Text, 58},
    {7, 0, kConfigFieldBaseId + 137, L"Ram Orientation", L"Monster", L"AlternateSkullRollDegrees", L"Ram roll degrees", L"90", ConfigFieldKind::Text, 58},
    {7, 0, kConfigFieldBaseId + 177, L"Threat Logic", L"Monster", L"MonsterIgnorePlayer", L"Ignore player", L"0", ConfigFieldKind::Bool, 0},
    {7, 0, kConfigFieldBaseId + 76, L"Threat Logic", L"Monster", L"MonsterKillDistance", L"Kill distance", L"1.18", ConfigFieldKind::Text, 90},
    {7, 0, kConfigFieldBaseId + 77, L"Threat Logic", L"Monster", L"MonsterVisibleDistance", L"Visible threat meters", L"12", ConfigFieldKind::Text, 90},
    {7, 0, kConfigFieldBaseId + 90, L"Dread Meter", L"Dread", L"Enabled", L"Enable dread", L"1", ConfigFieldKind::Bool, 0},
    {7, 0, kConfigFieldBaseId + 91, L"Dread Meter", L"Dread", L"DebugMeter", L"Show debug meter", L"0", ConfigFieldKind::Bool, 0},
    {7, 0, kConfigFieldBaseId + 176, L"Debug Overlay", L"Debug", L"AiMapOverlay", L"AI minimap overlay", L"0", ConfigFieldKind::Bool, 0},
    {7, 0, kConfigFieldBaseId + 177, L"Cheats", L"Debug", L"InfiniteStamina", L"Infinite stamina", L"0", ConfigFieldKind::Bool, 0},
    {7, 0, kConfigFieldBaseId + 178, L"Cheats", L"Debug", L"Invincible", L"Invincible", L"0", ConfigFieldKind::Bool, 0},
    {7, 0, kConfigFieldBaseId + 92, L"Dread Meter", L"Dread", L"DecayPerSecond", L"Decay per second", L"0.03", ConfigFieldKind::Text, 90},
    {7, 0, kConfigFieldBaseId + 93, L"Dread Meter", L"Dread", L"MonsterDistance", L"Monster pressure meters", L"13", ConfigFieldKind::Text, 90},
    {7, 0, kConfigFieldBaseId + 94, L"Dread Meter", L"Dread", L"MonsterGainPerSecond", L"Monster gain per sec", L"0.42", ConfigFieldKind::Text, 90},
    {7, 1, kConfigFieldBaseId + 95, L"Dread Response", L"Dread", L"JumpscareGain", L"Jumpscare gain", L"0.1", ConfigFieldKind::Text, 90},
    {7, 1, kConfigFieldBaseId + 96, L"Dread Response", L"Dread", L"FleshGain", L"Flesh flicker gain", L"0.2", ConfigFieldKind::Text, 90},
    {7, 1, kConfigFieldBaseId + 97, L"Dread Response", L"Dread", L"WalkSpeedBoost", L"Walk speed boost", L"0.05", ConfigFieldKind::Text, 90},
    {7, 1, kConfigFieldBaseId + 98, L"Dread Response", L"Dread", L"RunSpeedBoost", L"Run speed boost", L"0.075", ConfigFieldKind::Text, 90},
    {7, 1, kConfigFieldBaseId + 99, L"Dread Response", L"Dread", L"FlashlightFlicker", L"Flashlight flicker", L"1", ConfigFieldKind::Text, 90},
};

