#include "../platform/platform_headers.h"
#include "../core/maze_types.h"
#include "../core/math_utils.h"
#include "../core/constants.h"
#include "../debug/effect_debug_constants.h"

#include "settings.h"

#include "settings_paths.inl"
#include "settings_input_runtime.inl"
#include "settings_assets.inl"
#include "settings_profile.inl"
#include "settings_defaults.inl"
#include "settings_io.inl"
#include "settings_runtime_variation.inl"
