#include "renderer_lamp_hum_voice_tag.inl"
#include "renderer_lamp_hum_audible_candidate.inl"
#include "renderer_lamp_hum_update.inl"
#include "renderer_lamp_flicker_dim.inl"
#include "renderer_lamp_flicker_clicks.inl"
