#include "monster_presentation_header.inl"
#include "monster_presentation_reset.inl"
#include "monster_presentation_trail_prime.inl"
#include "monster_presentation_trail_record.inl"
#include "monster_presentation_self_avoidance.inl"
#include "monster_presentation_head_animation.inl"
