#include "monster_hearing_alert_sound.inl"
#include "monster_hearing_alert_player.inl"
#include "monster_hearing_wall_blocks.inl"
#include "monster_hearing_obstruction_chance.inl"
#include "monster_hearing_process_player_sounds.inl"
